<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOrder($col, $order = "ASC")
    {
        $dql = "SELECT user FROM UserBundle:User user ORDER BY user.".$col." ".$order;

        $query = $this->_em->createQuery($dql);

        return $query;
    }
}

